### PR TITLE
Add changes for Flink 1.0.1

### PR DESCRIPTION
**Pull request by rachel-orti**
Add changes for Flink samples for 1.0.1.

### CODE REVIEW

**Review by faraktingi — APPROVED** [review]
I approve the changes in this PR.
Flink Deployment with modified profiles have been tested successfully on our local pipeline build.
Thanks Rachel.

**Comment by rachel-orti** [comment]
@dibbles Please can you merge this PR when you think it will be appropriate ? Thanks.

**Review by AdrianVasiliu — APPROVED** [review]
Yes.

**Comment by faraktingi** [comment]
In order to be able to Tag the last IBM Event Automation Flink release 1.0.1. I merge this PR.

**Pull request merged**
